[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Only keep essential redirects
# Critical OAuth redirect for authentication
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/callback"
  status = 200
  force = true

# SPA fallback for React routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200