[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/callback"
  status = 200
  force = true

# Fix for canonicalization - redirect www to non-www
[[redirects]]
  from = "https://www.pastorbot.app/*"
  to = "https://pastorbot.app/:splat"
  status = 301
  force = true

# Add this rule to prevent loops with trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

# This must be the last redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200