[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Only the essential function proxy redirect
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/callback"
  status = 200

# SPA fallback with status 200 only, no force parameter
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200